/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.receitas_despesas.view;

import com.mycompany.receitas_despesas.model.Despesas;
import com.mycompany.receitas_despesas.model.GestorLancamentos;
import com.mycompany.receitas_despesas.model.Lancamentos;
import com.mycompany.receitas_despesas.model.Receitas;
import com.mycompany.receitas_despesas.model.TipoDespesas;
import com.mycompany.receitas_despesas.model.TipoReceitas;
import java.awt.event.ActionEvent;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author T-Gamer
 */
public class FazerLancamento extends javax.swing.JFrame {

    String tipo;
    private File arquivoCSV = null;

    /**
     * Creates new form FazerLancamento
     */
    public FazerLancamento() {
        initComponents();
        atualizarCategorias();
    }

    public void atualizarCategorias() {
        tipo = jCBTipo.getSelectedItem().toString();
        jCBCategoria.removeAllItems();

        switch (tipo) {
            case "Receita" -> {
                for (TipoReceitas r : TipoReceitas.values()) {
                    jCBCategoria.addItem(r.name());
                }
            }
            case "Despesa" -> {
                for (TipoDespesas r : TipoDespesas.values()) {
                    jCBCategoria.addItem(r.name());
                }
            }
        }

        if (jCBCategoria.getItemCount() > 0) {
            jCBCategoria.setSelectedIndex(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTADesc = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jTFValor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTData = new javax.swing.JTextField();
        jCBTipo = new javax.swing.JComboBox<>();
        jCBCategoria = new javax.swing.JComboBox<>();
        jBtArquivo = new javax.swing.JButton();
        jBtFechar = new javax.swing.JButton();
        jBtLancar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Fazer Lançamento"));

        jLabel1.setText("Tipo de Lançamento:");

        jLabel2.setText("Categoria:");

        jLabel3.setText("Descrição:");

        jTADesc.setColumns(20);
        jTADesc.setRows(5);
        jScrollPane1.setViewportView(jTADesc);

        jLabel4.setText("Valor:");

        jLabel5.setText("data de expedição:");

        jCBTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Receita", "Despesa", " " }));
        jCBTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBTipoActionPerformed(evt);
            }
        });

        jCBCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jBtArquivo.setText("Escolher Caminho");
        jBtArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtArquivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtArquivo)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTData, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                        .addComponent(jTFValor, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jCBCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jCBTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jCBCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTFValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jTData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jBtArquivo)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jBtFechar.setText("Fechar");
        jBtFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtFecharActionPerformed(evt);
            }
        });

        jBtLancar.setText("Lancar");
        jBtLancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtLancarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBtLancar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtFechar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtLancar)
                    .addComponent(jBtFechar))
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtFecharActionPerformed
        dispose();
    }//GEN-LAST:event_jBtFecharActionPerformed

    private void jBtLancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtLancarActionPerformed

        String tipo = jCBTipo.getSelectedItem().toString();
        String categoria = jCBCategoria.getSelectedItem().toString();
        double valor = Double.parseDouble(jTFValor.getText());

        String datas = jTData.getText();
        String descricao = jTADesc.getText();

        //Mudando a data de String para Date
        LocalDate data = null;
        try {
            DateTimeFormatter format = DateTimeFormatter.ofPattern("yyyy-MM-dd");
            data = LocalDate.parse(datas, format);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Data inválida. Use o formato yyyy-MM-dd.");
            return;
        }

        //Código para determinar qual objeto deve ser criado (Receita ou Despesa).
        Lancamentos lancamento;

        switch (tipo) {
            case "Receita" ->
                lancamento = new Receitas(categoria, descricao, valor, data);

            //verificação de saldo para lançar as despesas.
            case "Despesa" ->
                lancamento = new Despesas(categoria, descricao, valor, data);
            default -> {
                JOptionPane.showMessageDialog(this, "Tipo inválido.");
                return;
            }
        }

        GestorLancamentos.adicionar(lancamento);
        if (arquivoCSV != null) {
            boolean arquivoNovo = !arquivoCSV.exists();

            // Cria o arquivo com cabeçalho se ele ainda não existir
            if (arquivoNovo) {
                try (PrintWriter writer = new PrintWriter(new FileWriter(arquivoCSV, true))) {
                    writer.println("Tipo;Descricao;Valor;Data;Categoria");
                } catch (IOException e) {
                    JOptionPane.showMessageDialog(this, "Erro ao criar cabeçalho do CSV: " + e.getMessage());
                    return;
                }
            }

            // Usa o método reutilizável para salvar o lançamento
            GestorLancamentos.salvarCSV(lancamento, arquivoCSV);
        } else {
            JOptionPane.showMessageDialog(this, "Escolha um arquivo primeiro com o botão 'Caminho Arquivo'");
            return;
        }
        //Só para testes!
        JOptionPane.showMessageDialog(this, "Lançamento registrado como: " + lancamento.getTipo());

        jCBCategoria.setSelectedIndex(0);
        jTFValor.setText("");
        jTData.setText("");
        jTADesc.setText("");
        jCBTipo.setSelectedIndex(0);

    }//GEN-LAST:event_jBtLancarActionPerformed

    private void jCBTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBTipoActionPerformed
        atualizarCategorias();
        if (jCBCategoria.getSelectedItem() != null) {
            jCBCategoria.getSelectedItem().toString();
        }
    }//GEN-LAST:event_jCBTipoActionPerformed

    private void jBtArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtArquivoActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Escolha onde salvar o arquivo");
        fileChooser.setFileFilter(new FileNameExtensionFilter("Arquivos CSV", "csv"));

        int userSelection = fileChooser.showSaveDialog(this);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File arquivoEscolhido = fileChooser.getSelectedFile();

            if (!arquivoEscolhido.getName().toLowerCase().endsWith(".csv")) {
                arquivoEscolhido = new File(arquivoEscolhido.getParentFile(), arquivoEscolhido.getName() + ".csv");
            }

            arquivoCSV = arquivoEscolhido;
            JOptionPane.showMessageDialog(this, "Arquivo selecionado: " + arquivoCSV.getAbsolutePath());
        }
    }//GEN-LAST:event_jBtArquivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FazerLancamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FazerLancamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FazerLancamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FazerLancamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FazerLancamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtArquivo;
    private javax.swing.JButton jBtFechar;
    private javax.swing.JButton jBtLancar;
    private javax.swing.JComboBox<String> jCBCategoria;
    private javax.swing.JComboBox<String> jCBTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTADesc;
    private javax.swing.JTextField jTData;
    private javax.swing.JTextField jTFValor;
    // End of variables declaration//GEN-END:variables
}
