/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.receitas_despesas.view;

import com.mycompany.receitas_despesas.model.GestorLancamentos;
import com.mycompany.receitas_despesas.model.Lancamentos;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author T-Gamer
 */
public class Lancamento extends javax.swing.JFrame {
    
    /**
     * Creates new form Lancamento
     */
    public Lancamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jBDtAtual = new javax.swing.JButton();
        jBSemDt = new javax.swing.JButton();
        jBLancamento = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jBConsultar = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Lançamentos");

        jLabel3.setText("Ver Lançamentos: ");

        jBDtAtual.setText("Até Data Atual");
        jBDtAtual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDtAtualActionPerformed(evt);
            }
        });

        jBSemDt.setText("Todos");
        jBSemDt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSemDtActionPerformed(evt);
            }
        });

        jBLancamento.setText("Fazer Lançamento");
        jBLancamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLancamentoActionPerformed(evt);
            }
        });

        jLabel4.setText("Consultar Saldo:");

        jBConsultar.setText("Consultar");
        jBConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBLancamento)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBDtAtual)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBSemDt))
                            .addComponent(jBConsultar))))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jBDtAtual)
                    .addComponent(jBSemDt))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jBConsultar))
                .addGap(39, 39, 39)
                .addComponent(jBLancamento)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBDtAtualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDtAtualActionPerformed
        LancamentosFeitos dialog = new LancamentosFeitos(this, true);
        
        //Pega todos os lançamentos feitos até o dia anterior!
        ArrayList<Lancamentos> filtro = GestorLancamentos.getDatasPassadas();
        
        if (filtro.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nenhum lançamento em datas passadas.");
            return;
        }
        
        //StringBUilder para transformar os valores em String.
        StringBuilder sb = new StringBuilder();
            for (Lancamentos lanc : filtro) {
                sb.append(lanc.toString()).append("\n"); 
            }
            dialog.exibirTexto(sb.toString());
        
        
        dialog.setVisible(true); 
    }//GEN-LAST:event_jBDtAtualActionPerformed

    private void jBSemDtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSemDtActionPerformed
        LancamentosFeitos dialog = new LancamentosFeitos(this, true);
        
        //Pega todos os lançamentos feitos!
        ArrayList<Lancamentos> lancados = GestorLancamentos.getTodos();
        
        StringBuilder sb = new StringBuilder();
        for (Lancamentos l : lancados){
            sb.append(l.toString()).append("\n");
        }
        
        dialog.exibirTexto(sb.toString());
        
        dialog.setVisible(true); 
    }//GEN-LAST:event_jBSemDtActionPerformed

    private void jBLancamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLancamentoActionPerformed
        FazerLancamento lancar = new FazerLancamento();
        
        lancar.atualizarCategorias();
        
        lancar.setVisible(true);
        
    }//GEN-LAST:event_jBLancamentoActionPerformed

    private void jBConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsultarActionPerformed
        double saldoTotal = GestorLancamentos.getSaldo();
        double saldoData = GestorLancamentos.getSaldoDataPassadas();

        Saldo saldo = new Saldo(this, true);
        
        saldo.valorData(String.format("R$ %.2f", saldoData));
        saldo.valorTotal(String.format("R$ %.2f", saldoTotal));
        
        saldo.setVisible(true);
    }//GEN-LAST:event_jBConsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lancamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lancamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lancamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lancamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lancamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBConsultar;
    private javax.swing.JButton jBDtAtual;
    private javax.swing.JButton jBLancamento;
    private javax.swing.JButton jBSemDt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
